### ISSUE TITLE
Import roi_pooling,get error below

### ISSUE THREAD

**Issue by ccyxx** [deepsense-ai/roi-pooling#10]
"/lib/python2.7/site-packages/roi_pooling/roi_pooling.so: cannot open shared object file: No such file or directory"

**Comment by tgrel** [comment]
Are you sure you have CUDA installed on your system? Can you provide the output of `nvcc --version` command?

**Comment by Ahmad-Masood** [comment]
Actually, i'm facing the same issue. Any idea how to fix it
