### ISSUE TITLE
NotFoundError: roi_pooling.so

### ISSUE THREAD

**Issue by wagenrace** [deepsense-ai/roi-pooling#13]
Hey,
I have tried to build it but got the error
"NotFoundError: /opt/anaconda/lib/python3.6/site-packages/roi_pooling/roi_pooling.so: cannot open shared object file: No such file or directory"

Can someone help me? Is this a problem with anaconda?

**Comment by tgrel** [comment]
I haven't tried running the code using anaconda. What commands are you exactly issuing?

**Comment by wagenrace** [comment]
I ran the 'python setup.py install' command. This worked without error and within python 'roi_pooling' gets recognized as a package. But when I ran the example code I get the error of the missing roi_pooling.so

**Comment by tgrel** [comment]
Are you sure you have tensorflow installed? In what version?

**Comment by wagenrace** [comment]
I have tensorflow Install, I had 1.2. That didn't. I just upgraded to 1.4 that still didn't work.
I completely sure tensorflow works, other models are training fine

**Comment by tgrel** [comment]
I haven't tried it with neither 1.2 nor 1.4. I'm sure 1.0 is supported. Can you try it? If this doesn't help you can also try without anaconda.

**Comment by wagenrace** [comment]
But that would still mean I miss the file 'roi_pooling.so'. Where should that be created?

**Comment by tgrel** [comment]
It means the compilation of the c++ and CUDA code for the ROI pooling has silently failed, probably because some of the dependencies (TF, CUDA etc.) are unmet.

**Comment by wagenrace** [comment]
I am now downgrading tensorflow and reinstall the cuda toolkit. It seemed that was the problem 'make: nvcc: Command not found'

**Comment by wagenrace** [comment]
It seems I still get a problem with the building:
2 errors detected in the compilation of "/tmp/tmpxft_00007778_00000000-7_roi_pooling.cu.cpp1.ii".
Makefile:9: recipe for target 'roi_pooling.cu.o' failed
make: *** [roi_pooling.cu.o] Error 2

**Comment by tgrel** [comment]
@wagenrace do you still experience problems or have you managed to solve the issue?

**Comment by wagenrace** [comment]
I still experience the problem. I have moved to a different solution for my problem, thank you for your time!

**Comment by tgrel** [comment]
OK, I'm closing the issue
